### ISSUE TITLE
Build topology for data topic

### ISSUE THREAD

**Issue by klangner** [carldata/hydra#3]
This taks will require the following subtasks:
 * [ ] class Computation - should store compiled script instead of a string
 * [ ] Compile script in RTCommandProcessor
 * [x] DataProcessor copies data from triggered channel to the destination channel, but doesn't run scripts yet. Implement script execution and return result. Prepare testcase for it.
  * [ ] Deploy working container to the Azure (After PR is accepted)

**Comment by wenta** [comment]
Fixed.
